apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis-singleone
spec:
  selector:
    app: redis
  type: ClusterIP
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
