apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: jenkins-admin    ## pod 的 sa 用户指定为具有管理员权限的 sa 用户
      containers:
        - name: jenkins
          image: jenkins/jenkins:2.387.1-lts-jdk11
          env:
            - name: JENKINS_JAVA_OPTIONS
              value: -Duser.timezone=Asia/Shanghai
          resources:
            limits:
              memory: "1.5Gi"
              cpu: "1500m"
            requests:
              memory: "500Mi"
              cpu: "10m"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          startupProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-data-home
              mountPath: /var/jenkins_home
            - name: localtime
              mountPath: /etc/localtime
      volumes:
        - name: jenkins-data-home
          persistentVolumeClaim:
              claimName: jenkins-data
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
