# 创建 jenkins-admin sa 账户
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: devops-tools

---
# - 创建 jenkins-admin 角色 ( 以下权限是 pod 操作权限，主要是为了可以让 jenkins 可以在集群中动
# 态创建 pod 作为构建使用的 slave 代理 )
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-admin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
# 将 jenkins-admin sa 绑定到 jenkins-admin 角色
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-admin
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: devops-tools
