apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  namespace: elasticsearch
spec:
  selector:
    app: elasticsearch-master
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: elasticseatch
    protocol: TCP
    port: 9200
    targetPort: 9200
    # nodePort: 30804
