apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master-headless
  namespace: elasticsearch
spec:
  selector:
    app: elasticsearch-master
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: elastic-http
    protocol: TCP
    port: 9200
    targetPort: 9200
  - name: elastic-cluster
    protocol: TCP
    port: 9300
    targetPort: 9300
