apiVersion: v1
kind: Service
metadata:
  name: rocketmq-nameserver-headless
  namespace: rocketmq
spec:
  selector:
    app: rocketmq-nameserver
  # type: ClusterIP
  # clusterIP: None
  type: ClusterIP
  clusterIP: None
  # sessionAffinity: ClientIP
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  # ports:
  #   - name: namesrv-9876
  #     protocol: TCP
  #     port: 9876
  #     targetPort: 9876
      # nodePort: 0
