apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: nacos
spec:
  selector:
    app: nacos
  type: ClusterIP
  clusterIP: None
  # 无头服务不会分配集群内 IP 地址无需指定端口
  # ports:
  #   - name: http
  #     protocol: TCP
  #     port: 8848
  #   - name: cluster
  #     protocol: TCP
  #     port: 7848
  #   - name: grpc-client
  #     protocol: TCP
  #     port: 9848
  #   - name: grpc-server
  #     protocol: TCP
  #     port: 9849
