apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: nacos
spec:
  selector:
    app: nacos
  type: NodePort
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
    - name: nacos
      protocol: TCP
      port: 8848
      targetPort: 8848
